gp_editor={sortable_area_sel:".gp_gallery",img_name:"gallery",img_rel:"gallery_gallery",edit_links_target:!1,auto_start:!1,make_sortable:!0,updateCaption:function(){},removeImage:function(){},removedImage:function(){},addedImage:function(){},editorLoaded:function(){},widthChanged:!1,heightChanged:!1,intervalSpeed:!1,moveBack:!1,moveForward:!1,checkDirty:function(){return!1},getData:function(b){var g={images:[],captions:[]};b.find(gp_editor.sortable_area_sel).find("li > a").each(function(){g.images.push($(this).attr("href"))});
b.find(gp_editor.edit_links_target).find(".caption").each(function(){g.captions.push($(this).html())});var l=$("#gp_gallery_options").find("input,select").serialize();b=b.clone();b.find("li.holder").remove();b.find("ul").enableSelection().removeClass("ui-sortable").removeAttr("unselectable");b.find(".gp_nosave").remove();b=b.html();return $.param(g)+"&"+l+"&gpcontent="+encodeURIComponent(b)},updateElement:function(){}};
function gp_init_inline_edit(b,g){function l(a,f){h.find(".gp_to_remove").remove();a.attr({"data-cmd":gp_editor.img_name,"data-arg":gp_editor.img_rel,title:"","class":gp_editor.img_rel});var c=$("<li>").append(a).append('<div class="caption"></div>');f?f.replaceWith(c):e.append(c);c.trigger("gp_gallery_add");gp_editor.addedImage(c)}$gp.LoadStyle("/include/css/inline_image.css");"undefined"!==typeof gp_gallery_options&&$.extend(gp_editor,gp_gallery_options);gp_editor.edit_links_target||(gp_editor.edit_links_target=
gp_editor.sortable_area_sel+" > li");var d=!1,m=!1,j=!1,e,k=gp_editing.get_path(b),h=gp_editing.get_edit_area(b);if(!(!1==h||!1==k)){gp_editor.save_path=k;gp_editor.destroy=function(){e.filter(":ui-sortable").sortable("destroy");h.html(m.html());e.children("li").unbind("mouseenter.gp_edit, mouseleave.gp_edit, mousedown.gp_edit");d.remove()};gp_editor.checkDirty=function(){e.removeClass("ui-sortable");var a=m.html().replace(/>[\s]+/g,">"),f=h.html().replace(/>[\s]+/g,">");if(a!=f)return e.addClass("ui-sortable"),
!0;e.addClass("ui-sortable");return!1};gp_editor.gp_saveData=function(){return gp_editor.getData(h,gp_editor)};gp_editor.resetDirty=function(){m=h.clone(!1);m.find(".ui-sortable").removeClass("ui-sortable")};h.get(0).innerHTML=g.content;var n=function(a,f,c){a.append('<a data-cmd="'+f+'"><img src="'+gpBase+'/include/imgs/blank.gif" height="16" width="16" class="'+c+'"/></a>')};e=h.find(gp_editor.sortable_area_sel);gp_editor.make_sortable&&(e.sortable({placeholder:"gp_drag_box",opacity:0.6,tolerance:"pointer",
beforeStop:function(a,f){f.item.removeAttr("style").removeAttr("class")}}),e.disableSelection());gp_editor.resetDirty();strip_from(k,"?");gp_editing.editor_tools();$("#ckeditor_top").html('<div id="gp_image_area"></div><div id="gp_upload_queue"></div>');$("#ckeditor_controls").prepend('<div id="gp_folder_options"></div>');LoadImages(!1,gp_editor);k=$('<div id="gp_gallery_options">').prependTo("#ckeditor_save");if(gp_editor.heightChanged)$('<div class="half_width">'+gplang.Height+': <input class="ck_input" type="text" name="height" /></div>').appendTo(k).find("input").val(g.height).on("keyup paste change",
gp_editor.heightChanged);gp_editor.widthChanged&&(debug(gp_editor.widthChanged),$('<div class="half_width">'+gplang.Width+': <input class="ck_input" type="text" name="width" /></div>').appendTo(k).find("input").val(g.width).on("keyup paste change",gp_editor.widthChanged));gp_editor.auto_start&&(gplang.Auto_Start="Auto Start",$('<div class="half_width">'+gplang.Auto_Start+': <input class="ck_input" type="checkbox" name="auto_start" value="true" /></div>').appendTo(k).find("input").prop("checked",g.auto_start));
gp_editor.intervalSpeed&&(gplang.Speed="Speed",$('<div class="half_width">'+gplang.Speed+': <input class="ck_input" type="text" name="interval_speed" /></div>').appendTo(k).find("input").val(g.interval_speed).on("keyup paste change",gp_editor.intervalSpeed));d=$('<span class="gp_gallery_edit gp_floating_area"></span>').appendTo("body").hide();if(gp_editor.moveBack)$("<a>&lsaquo;</a>").appendTo(d).on("click",function(){gp_editor.moveBack(j)});if(gp_editor.moveForward)$("<a>&rsaquo;</a>").appendTo(d).on("click",
function(){gp_editor.moveForward(j)});n(d,"gp_gallery_caption","page_edit");n(d,"gp_gallery_rm","delete");d.bind("mouseenter.gp_edit",function(){d.show()}).bind("mouseleave.gp_edit",function(){d.hide()});$(document).delegate(gp_editor.edit_links_target,{"mousemove.gp_edit":function(){var a=$(this).offset();d.show().css({left:a.left,top:a.top});j=this},"mouseleave.gp_edit":function(){d.hide()},"mousedown.gp_edit":function(){d.hide()}});$gp.links.gp_gallery_caption=function(){d.hide();var a=$(j),a=
a.find(".caption").html()||a.find("a:first").attr("title"),a='<div class="inline_box" id="gp_gallery_caption"><form><h3>'+gplang.cp+'</h3><textarea name="caption" cols="50" rows="3">'+$gp.htmlchars(a)+'</textarea><p><input type="submit" name="cmd" value="'+gplang.up+'" class="gp_gallery_update" /> <input type="button" name="" value="'+gplang.ca+'" class="admin_box_close" /></p></form></div>';$gp.AdminBoxC(a)};$gp.links.gp_gallery_rm=function(){gp_editor.removeImage(j);$(j).remove();d.hide();gp_editor.removedImage(h)};
gpinputs.gp_gallery_update=function(a){a.preventDefault();a=$(this.form).find("textarea").val();var f=$(j).find(".caption");f.html(a);a=f.html();$gp.CloseAdminBox();gp_editor.updateCaption(j,a)};gp_editor.editorLoaded();$gp.links.gp_gallery_add=function(a){a.preventDefault();a=$(this).stop(!0,!0);l(a.clone());a.parent().fadeTo(100,0.2).fadeTo(2E3,1)};$gp.links.gp_gallery_add_all=function(a){a.preventDefault();$("#gp_gallery_avail_imgs").find("a[name=gp_gallery_add],a[data-cmd=gp_gallery_add]").each(function(){l($(this).clone())})};
gpresponse.gp_gallery_images=function(){var a=$("#gp_upload_form");a.attr("action");a.find(".file").auto_upload({start:function(a,c){c.bar=$('<a data-cmd="gp_file_uploading">'+a+"</a>").appendTo("#gp_upload_queue");c.holder=$('<li class="holder" style="display:none"></li>').appendTo(e);return!0},progress:function(a,c,d){a=Math.round(100*a);a=Math.min(98,a-1);d.bar.text(a+"% "+c)},finish:function(a,c,d){var b=d.bar;b.text("100% "+c);var e=$(a);a=e.find(".status").val();e=e.find(".message").val();"success"==
a?(b.addClass("success"),b.slideUp(1200),c=$("#gp_gallery_avail_imgs"),c=$(e).appendTo(c).find("a[name=gp_gallery_add],a[data-cmd=gp_gallery_add]"),l(c.clone(),d.holder)):"notimage"==a?b.addClass("success"):(b.addClass("failed"),b.text(c+": "+e))},error:function(a,c,b){alert("error: "+b)}})};$gp.links.gp_file_uploading=function(){var a=$(this),b=!1;a.hasClass("failed")?b=!0:a.hasClass("success")&&(b=!0);b&&a.slideUp(700)};gpinputs.gp_gallery_folder_add=function(a,b){b.preventDefault();var c=this.form;
LoadImages(c.dir.value+"/"+c.newdir.value,gp_editor)}}};