var gp_editor=!1,debug_area;function debug(a){debug_area||(debug_area=$('<div id="debug" style="position:absolute;top:0;left:0;background:#fff;padding:10px;z-index:99999;border:1px solid #333;max-width:30%;white-space:pre-wrap">').prependTo("body"));debug_area.prepend("<div>"+LOGO(a)+"</div><hr/>")}
function LOGO(a){var b,c=typeof a,d="\n<br/> ("+c+") ";if("object"===c)for(b in a){if(a.hasOwnProperty(b)){d+="\n<b>"+b+"</b> = ";try{d+=$gp.htmlchars(a[b])}catch(h){d+=" -- not allowed -- "}}}else d+=$gp.htmlchars(a);return d}$gp.Coords=function(a){a.hasClass("inner_size")&&(a=a.children(":first"));var b=a.offset();b.w=a.outerWidth();b.h=a.outerHeight();return b};$gp.div=function(a){var b=$("#"+a);0===b.length&&(b=$('<div id="'+a+'"></div>').appendTo("#gp_admin_html"));return b};
$gp.links.iadmin_box=function(a,b){a.preventDefault();$gp.CopyVals(b,this);$gp.AdminBoxC($(b),"inline")};$gp.links.inline_edit_generic=function(a,b){a.preventDefault();$gp.loading();if("function"===typeof gplinks[b])gplinks[b].call(this,b,a);else{$gp.LoadStyle("/include/css/inline_edit.css");var c=strip_from(this.href,"#"),d=$(this).attr("id").substr(13);$.getScript(c+"&cmd=inlineedit&area_id="+d,function(a){"false"===a&&(alert($gp.error),$gp.loaded())})}};
$gp.LoadStyle=function(a){var b=(new Date).getTime();$('<link rel="stylesheet" type="text/css" />').appendTo("head").attr({href:gpBase+a+"?t="+b})};
$gp.AdminBoxC=function(a,b){$gp.CloseAdminBox();if(""===a)return!1;var c=$(window),d=Math.round((c.width()-640-40)/2),h=Math.max($(document).height(),$("body").outerHeight(!0));$gp.div("gp_admin_box1").css({zIndex:11E3,"min-height":h}).stop(!0,!0,!0).fadeTo(0,0).fadeTo(200,0.2);$gp.div("gp_admin_box").css({zIndex:"11001",left:d,top:c.scrollTop()}).stop(!0,!0,!0).fadeIn(400).html('<a class="gp_admin_box_close" data-cmd="admin_box_close"></a><div id="gp_admin_boxc" class="'+(b||"")+'" style="width:640px"></div>').find("#gp_admin_boxc").html(a).find("input:visible:first").focus();
$(".messages").detach();return!0};$gp.CloseAdminBox=function(a){a&&a.preventDefault();$("#gp_admin_box1").fadeOut();$("#gp_admin_box").fadeOut(300,function(){$("#gp_admin_boxc").hasClass("inline")?$("#gp_admin_boxc").children().appendTo("#gp_hidden"):$("#gp_admin_boxc").children().remove()});"undefined"!==typeof $.fn.colorbox&&$.fn.colorbox.close()};$gp.links.admin_box_close=gpinputs.admin_box_close=$gp.CloseAdminBox;
$gp.links.remote=function(a){a.preventDefault();var b=strip_from(window.location.href,"#");a=$gp.jPrep(this.href,"gpreq=body");gpRem&&(a+="&in="+encodeURIComponent(b)+"&blink="+encodeURIComponent(gpBLink));b=$(window).height()-130;$gp.AdminBoxC('<iframe src="'+a+'" style="height:'+b+'px;" frameborder="0" />',"iframe")};$gp.SaveGPUI=function(){if(isadmin){var a="cmd=savegpui";$.each(gpui,function(b,c){a+="&gpui_"+b+"="+c});$gp.postC(window.location.href,a)}};
$gp.links.dd_menu=function(a){a.preventDefault();a.stopPropagation();$(".messages").detach();var b=this,c=$(this).parent().find(".dd_list");c.show();if(c.find(".selected").length){a=c.find("ul:first");var d=c.find(".selected").prev().prev().prev().position();d&&a.scrollTop(d.top+a.scrollTop())}$("body").on("click.gp_select",function(a){c.hide();c.off(".gp_select");$("body").off(".gp_select");$(a.target).closest(b).length&&a.stopPropagation()})};
$gp.links.tabs=function(a){a.preventDefault();a=$(this);a.siblings("a").removeClass("selected").each(function(a,c){c.hash&&$(c.hash).hide()});this.hash&&(a.addClass("selected"),$(this.hash).show())};$gp.Loaded={};$gp.LoadScripts=function(a,b,c){function d(){h--;0===h&&"function"===typeof b&&b.call(this)}var h=a.length,f=(new Date).getTime(),e="";c&&(e=gpBase);$.each(a,function(a,b){b=e+b;$gp.Loaded[b]?d():($gp.Loaded[b]=!0,$.getScript($gp.jPrep(b,"t="+f),function(){d()}))})};
$gp.links.gp_refresh=function(a){a.preventDefault();$gp.Reload()};$gp.links.toggle_panel=function(a){var b=$("#simplepanel");a.preventDefault();var c="";b.hasClass("minb")?(c="",a=0):b.hasClass("compact")?(c="minb toggledmin",a=3):(c="compact",a=1);b.hasClass("toggledmin")||b.unbind("mouseenter touchstart").bind("mouseenter touchstart",function(a){b.unbind(a).removeClass("toggledmin")});b.attr("class","keep_viewable "+c);gpui.cmpct=a;$gp.SaveGPUI()};
$gp.links.toplink=function(){var a=$(this);if(!$("#simplepanel").hasClass("compact")){var b=a.next(),c=b.is(":visible")&&0<b.height();$("#simplepanel .panelgroup2:visible").slideUp(300);gpui.vis=!1;c||(gpui.vis=a.data("arg"),b.slideDown(300));$gp.SaveGPUI()}};
$gp.links.collapsible=function(){var a=$(this).parent();a.hasClass("one")&&a.hasClass("gp_collapsed")?(a.parent().find(".head").addClass("gp_collapsed"),a.parent().find(".collapsearea").slideUp(300),a.removeClass("gp_collapsed").next().slideDown(300)):a.toggleClass("gp_collapsed").next().slideToggle(300)};
$gp.links.ajax_box=$gp.links.admin_box=function(a){debug(' "ajax_box" and "admin_box" are deprecated link arguments');a.preventDefault();$gp.loading();a=$gp.jPrep(this.href,"gpreq=flush");$.get(a,"",function(a){$gp.AdminBoxC(a);$gp.loaded()},"html")};$gp.links.gpabox=function(a){a.preventDefault();$gp.loading();a=$gp.jPrep(this.href)+"&gpx_content=gpabox";$.getJSON(a,$gp.Response)};
$gp.links.add_table_row=function(){var a=$(this).closest("tr"),b=a.closest("tbody").find("tr:first").clone();b.find(".class_only").remove();b.find("input").val("");a.before(b)};$gp.inputs.gpabox=function(){return $gp.post(this,"gpx_content=gpabox")};$gp.inputs.gpcheck=function(){this.checked?$(this).parent().addClass("checked"):$(this).parent().removeClass("checked")};$gp.inputs.check_all=function(){$(this).closest("form").find("input[type=checkbox]").prop("checked",this.checked)};
$gp.inputs.cnreq=function(a){a.preventDefault();a=$(this.form).serialize();$gp.Cookie("cookie_cmd",encodeURIComponent(a),1);window.location=strip_from(strip_from(this.form.action,"#"),"?")};$gp.htmlchars=function(a){return $("<a>").text(a||"").html()};$gp.response.location=function(a){window.setTimeout(function(){window.location=a.SELECTOR},a.CONTENT)};
$(function(){$(document).on("mousedown","form",function(){var a=$(this);"checked"!==a.data("gpForms")&&("undefined"!==typeof this["return"]&&(this["return"].value=window.location),a.data("gpForms","checked"))});if(isadmin&&"undefined"===typeof gp_bodyashtml){var a=$("#admincontainer");1>a.length||($("#gpAfterContent").css("margin-top",a.height()+100),SimpleDrag("#admincontent_panel",a,"absolute",function(b){gpui.pposx=b.left;gpui.pposy=b.top;a.css({left:Math.max(5,gpui.pposx),top:Math.max(5,gpui.pposy)});
$gp.SaveGPUI()}));$("body").addClass("gpAdmin").trigger("AdminReady");window.setTimeout(function(){var a=function(a){a&&(a.hasClass("gp_editing")||a.removeClass("gp_no_overlay"))},c=function(){if(l&&!p){var a=l.offset(),b=l.position(),f=$(window).scrollTop(),a=Math.max(0,f-(a.top-b.top));l.stop(!0,!0,!0).animate({top:a})}},d=function(){e&&window.clearTimeout(e);e=window.setTimeout(function(){h()},200)},h=function(){j=!1;g.find("span").stop(!0,!0).hide(500);g.find("div").stop(!0,!0).fadeOut()},f=function(){l.addClass("gp_hover").stop(!0,
!0).show();n.stop(!0,!0).fadeIn()},e=!1,g,l=!1,j,n,p=!1;g=$gp.div("gp_edit_overlay");g.click(function(a){var b=$(a.target);0<b.filter("a").length&&(b.hasClass("gp_overlay_close")&&a.preventDefault(),j&&j.addClass("gp_no_overlay"));h()}).on("mouseleave touchend",function(){d()}).on("mouseenter touchstart",function(){e&&window.clearTimeout(e)});$(".editable_area").bind("mousemove.gp mouseenter.gp touchstart.gp",function(m){e&&window.clearTimeout(e);var k=$(this);0<k.parent().closest(".editable_area").length&&
m.stopPropagation();if(!(j&&k.attr("id")===j.attr("id"))){j&&a(j);j=k;a:{var d=j;if(!d.hasClass("gp_no_overlay")){k=d.attr("id").substr(13);m=$("#ExtraEditLnks"+k).find("a");if(0===m.length&&(m=$("#ExtraEditLink"+k),0===m.length))break a;k=$gp.Coords(d);g.show().css({top:k.top-3,left:k.left-2,width:k.w+6});l?l.stop(!0,!0).show().removeClass("gp_hover"):(l=$("<span>"),n=$("<div>"),g.html(n).append(l));n.stop(!0,!0).hide().css({height:k.h+5,width:k.w+4});c();m=m.clone(!0).removeClass("ExtraEditLink");
p=!1;l.css({left:"auto",top:0,right:0,position:"absolute"}).html('<a class="gp_overlay_expand"></a>').append(m).unbind("mouseenter touchstart").one("mouseenter touchstart",function(){d.hasClass("gp_no_overlay")||f()})}}}}).bind("mouseleave touchend",function(){d();a(j)});$(window).scroll(function(){c()});$(document).on("contextmenu",".editable_area, #gp_edit_overlay",function(a){if(!a.ctrlKey&&(!a.altKey&&!a.shiftKey&&!gp_editor)&&l){a.preventDefault();var b=$(window);f();var c=a.pageX-b.scrollLeft(),
d=c+l.width()-b.width();0<d&&(c-=d);l.css({top:a.pageY-b.scrollTop(),left:c,right:"auto",position:"fixed"});p=!0}});$("#current_page_panel").bind("mouseenter.edb touchstart.edb",function(){var a=0,b,f=$(window),c=$("#editable_areas_list").html("");b=$gp.div("gp_edit_box");$("a.ExtraEditLink").clone(!1).attr("class","").css("display","block").show().each(function(){var d,e,j;e=$(this);var g=e.attr("id").substr(13);j=$("#ExtraEditArea"+g);if(j.hasClass("gp_no_overlay")||0===j.length)return!0;a++;d=
this.title.replace(/_/g," ");d=decodeURIComponent(d);15<d.length&&(d=d.substr(0,14)+"...");e.attr("id","editable_mark"+g).text(d).appendTo(c).wrap("<li>").on("mouseenter touchstart",function(){var a=$gp.Coords(j);b.stop(!0,!0,!0).css({top:a.top-3,left:a.left-2,width:a.w+4,height:a.h+5}).fadeIn();(f.scrollTop()>a.top||f.scrollTop()+f.height()<a.top)&&$("html,body").stop(!0,!0,!0).animate({scrollTop:Math.max(0,a.top-100)},"slow")}).on("mouseleave touchend",function(){b.stop(!0,!0,!0).fadeOut()}).click(function(){$(this).unbind("mouseenter touchstart");
window.setTimeout(function(){$(this).remove();b.hide()},100)})})});SimpleDrag("#simplepanel .toolbar, #simplepanel .toolbar a","#simplepanel","fixed",function(a){gpui.tx=a.left;gpui.ty=a.top;$gp.SaveGPUI()},!0);admin_resizable?SimpleResize("#admincontainer",{min_w:300,finish:function(a,b){gpui.pposx=b;gpui.pw=a;$gp.SaveGPUI()}}):$("#admincontainer").css("width","auto");$(".in_window").parent().bind("mouseenter touchstart",function(){var a=$(this).children(".in_window").css({right:"auto",left:"100%",
top:0});window.setTimeout(function(){var b=a.offset(),f=b.left+a.width(),b=b.top+a.height(),c=$(window);f>c.width()+c.scrollLeft()&&a.css({right:"100%",left:"auto"});f=c.height()+c.scrollTop();b>f&&a.css({top:f+-b-10})},1)})},500);$(document).on("keyup keypress paste change",".show_character_count",function(){$(this).parent().find(".character_count span").html(this.value.length)});$(window).on("beforeunload",function(){if(gp_editor&&"undefined"!==typeof gp_editor.checkDirty&&gp_editor.checkDirty())return"Unsaved changes will be lost."})}});
function SimpleDrag(a,b,c,d){function h(a,b){if(a.hasClass("keep_viewable")){var c="fixed"===a.css("position"),d,e={};d=a.position();c&&(d.left-=g.scrollLeft(),d.top-=g.scrollTop());if(b)a.data({gp_left:d.left,gp_top:d.top});else if(c=a.data("gp_left"))d.left=e.left=c,d.top=e.top=a.data("gp_top");var c=a.width(),h=g.height();d.top<f?e.top=f:d.top>h&&(e.top=h+2*f);c=g.width()-c-f;d.left>c&&(e.left=c);(e.left||e.top)&&a.css(e)}}var f=-10,e=$(b),g=$(window),l=$(document);$(document).off("mousedown.sdrag",
a).on("mousedown.sdrag",a,function(a){var b,h,m;a.preventDefault();if(!(1>e.length)){var k=e.offset();h=a.clientX-k.left+g.scrollLeft();m=a.clientY-k.top+g.scrollTop();l.bind("mousemove.sdrag",function(a){if(!b){var c=e.offset(),d=e.width(),g=e.height();b=$gp.div("admin_drag_box").css({top:c.top,left:c.left,width:d,height:g})}b.css({left:Math.max(f,a.clientX-h),top:Math.max(f,a.clientY-m)});a.preventDefault();return!1});l.unbind("mouseup.sdrag").bind("mouseup.sdrag",function(a){var j,k,q;l.unbind("mousemove.sdrag mouseup.sdrag");
if(!b)return!1;a.preventDefault();b.remove();b=!1;j=a.clientX-h;k=a.clientY-m;"absolute"===c&&(j+=g.scrollLeft(),k+=g.scrollTop());j=Math.max(f,j);k=Math.max(f,k);q={left:j,top:k};e.css(q).data({gp_left:j,gp_top:k});"function"===typeof d&&d.call(e,q,a);return!1});return!1}});("fixed"===e.css("position")||"fixed"===e.parent().css("position"))&&h(e.addClass("keep_viewable"),!0);g.resize(function(){$(".keep_viewable").each(function(){h($(this),!1)})})}
$gp.response.renameprep=function(){function a(){h.val().replace(/_/g," ").toLowerCase()!==d?$("#gp_rename_redirect").show(500):$("#gp_rename_redirect").hide(300)}function b(){var b=$("input.title_label").val();$("input.new_title.sync_label").val(c(b));$("input.browser_title.sync_label").val(b);a();return!0}function c(a){a=a.replace(/[\x00-\x1F\x7F]/g,"");a=a.replace(/(\?|\*|:|#)/g,"");a=a.replace(/(<(\/?[a-zA-Z0-9][^<>]*)>)/ig,"");a=a.replace(/[\\]/g,"/");a=a.replace(/^\.+[\/\/]/,"/");a=a.replace(/[\/\/]\.+$/,
"/");a=a.replace(/[\/\/]\.+[\/\/]/g,"/");a=a.replace(/[\/\/]+/g,"/");a="."===a?"":a.replace(/^\/\/*/g,"");return a.replace(/ /g,"_")}var d,h;d=$("#gp_rename_form").find("input[name=old_title]").val().toLowerCase();h=$("input.new_title");b();$("input[disabled=disabled]").each(function(a,b){$(b).fadeTo(400,0.6)});$("input.title_label").bind("keyup change",b);$(".label_synchronize a").click(function(a){a.preventDefault();a=$(this).closest("td");var c=a.find("a:visible");a.find("a").show();c.hide();c=
a.find("a:visible");c.length&&(c.hasClass("slug_edit")?(a.find("input").addClass("sync_label").prop("disabled","disabled").fadeTo(400,0.6),b()):a.find("input").removeClass("sync_label").prop("disabled","").fadeTo(400,1))});$gp.links.showmore=function(){$("#gp_rename_table tr").show(500);$(this).parent().remove()};h.bind("keyup change",function(){a()})};
function SimpleResize(a,b){b=$.extend({},{max_w:1E4,min_w:0,finish:function(){}},b);var c=$(a);if(!(1>c.length))$('<span class="gp_admin_resize"></span><span class="gp_admin_resize gp_resize_right"></span>').appendTo(c).on("mousedown.sres",function(a){var h=a.clientX,f=c.width(),e=f,g=c.position().left,l=g,j=$(this).hasClass("gp_resize_right"),n=new Date;a.preventDefault();$('<div style="position:fixed;top:0;right:0;bottom:0;left:0;cursor:e-resize;z-index:999000;">').appendTo("body").on("mousemove.sres",
function(a){var d=new Date;if(!(200>d-n))return n=d,j?f=a.clientX-h+e:(g=a.clientX-h+l,f=h-a.clientX+e,g=Math.max(0,g),c.css({left:g})),f=Math.min(b.max_w,f),f=Math.max(b.min_w,f),c.width(f).resize(),!1}).off("mouseup.sres").on("mouseup.sres",function(a){a.preventDefault();$(this).off("mousemove.sres mouseup.sres").remove();b.finish.call(c,f,g);return!1});return!1})}
"function"!==typeof $.fn.disableSelection&&($.fn.disableSelection=function(){return $(this).attr("unselectable","on").css("-moz-user-select","none").each(function(){this.onselectstart=function(){return!1}})},$.fn.enableSelection=function(){return $(this).attr("unselectable","off").css("-moz-user-select","").each(function(){this.onselectstart=function(){return!1}})});