var $gp={inputs:{},response:{},error:"There was an error processing the last request. Please reload this page to continue.",jGoTo:function(a){$gp.loading();a=$gp.jPrep(a);$.getJSON(a,$gp.Response)},cGoTo:function(a,b){$gp.Cookie("cookie_cmd",encodeURIComponent(a.search+"&verified="+post_nonce),1);b?$gp.Reload():window.location=strip_from(strip_from(a.href,"#"),"?")},post:function(a,b){$gp.loading();var d=$(a).closest("form"),c=d.serialize()+"&verified="+encodeURIComponent(post_nonce);"INPUT"===a.nodeName&&
(c+="&"+encodeURIComponent(a.name)+"="+encodeURIComponent(a.value));b&&(c+="&"+b);$.post($gp.jPrep(d.attr("action")),c,$gp.Response,"json");return!1},post_link:function(a){$gp.loading();var b=$(a),b=strip_to(a.search,"?")+"&gpreq=json&jsoncallback=?&verified="+encodeURIComponent(b.data("nonce"));$.post(strip_from(a.href,"?"),b,$gp.Response,"json")},postC:function(a,b,d,c){d=d||$gp.Response;c=c||"json";"object"===typeof b&&(b=$.param(b));b+="&verified="+encodeURIComponent(post_nonce);"json"===c&&(b+=
"&gpreq=json&jsoncallback=?");$.post(strip_from(a,"?"),b,d,c)},cboxSettings:function(a){a=a||{};colorbox_lang=colorbox_lang||{};return $.extend(colorbox_lang,{opacity:0.75,maxWidth:"90%",maxHeight:"90%"},a)},Cookie:function(a,b,d){var c="";d&&(c=new Date,c.setTime(c.getTime()+864E5*d),c="; expires="+c.toGMTString());document.cookie=a+"="+b+c+"; path=/"},jPrep:function(a,b){b="undefined"===typeof b?"gpreq=json&jsoncallback=?":b;a=strip_from(a,"#");a+=-1===a.indexOf("?")?"?":"&";return a+b},Response:function(a,
b,d){$(".messages").detach();try{$gp.CloseAdminBox()}catch(c){}try{$.fn.colorbox.close()}catch(e){}$.each(a,function(a,c){if("function"===typeof $gp.response[c.DO])$gp.response[c.DO].call(this,c,b,d);else if("function"===typeof gpresponse[c.DO])gpresponse[c.DO].call(this,c,b,d);else switch(c.DO){case "replace":console.log(c.CONTENT);$(c.SELECTOR).replaceWith(c.CONTENT);break;case "inner":$(c.SELECTOR).html(c.CONTENT);break;case "admin_box_data":$gp.AdminBoxC(c.CONTENT);break;case "messages":$(c.CONTENT).appendTo("body").show().css({top:0})}});
$gp.loaded()},loading:function(){$("#loading1").css("zIndex",99E3).fadeTo(1,0.3).next().css("zIndex",99001).show()},loaded:function(){$("#loading1, #loading2").clearQueue().hide()},CopyVals:function(a,b){var d=$(a).find("form").get(0);d&&$(b).find("input").each(function(b,a){d[a.name]&&(d[a.name].value=a.value)})},Reload:function(){typeof req_type&&"post"==req_type?window.location.href=strip_from(window.location.href,"#"):window.location.reload(!0)},links:{gallery:function(a,b){a.preventDefault();
b=""===b?this:"a[rel="+b+"],a."+b;$.colorbox.remove();$(b).colorbox($gp.cboxSettings({resize:!0,rel:b}));$.colorbox.launch(this)}}};
$(function(){function a(b){$(b).filter("[method=post]").append('<input type="hidden" name="verified" value="'+post_nonce+'" />')}$("body").addClass("STCLASS");$gp.Cookie("cookie_cmd","",-1);$(document).ajaxError(function(b,a,c,e){$gp.loaded();"function"!==typeof c.error&&""!=e&&("undefined"!==typeof debugjs?(b={thrownError:e,text:a.responseText,status:a.status,statusText:a.statusText,url:c.url,type:c.type,browser:$.param($.browser)},c.data&&(b.data=c.data.substr(0,100)),"function"===typeof debug&&
debug(b)):alert($gp.error))});$(document).on("click","input",function(b){a(this.form);var d=$(this),c=d.data("cmd");c||(c=strip_from(d.attr("class")," "));if("function"===typeof $gp.inputs[c])return $gp.inputs[c].call(this,b);if("function"===typeof gpinputs[c])return gpinputs[c].call(this,b,b);switch(c){case "testsave":return b=this.form.action,d="&cmd=save&newcontentstring",$gp.postC(b,d),!1;case "gppost":case "gpajax":return $gp.post(this)}return!0});$(document).on("submit","form",function(){a(this)});
$(document).delegate(".expand_child",{mouseenter:function(){var a=$(this).addClass("expand");a.hasClass("simple_top")&&a.addClass("simple_top_hover")},mouseleave:function(){$(this).removeClass("expand simple_top_hover")}});$(document).on("click","a",function(a){var d=$(this),c=d.data("cmd"),e=d.data("arg");c||(c=d.attr("name"),e=d.attr("rel"));if(d.hasClass("gpconfirm")&&!confirm(this.title))a.preventDefault();else{if("function"===typeof $gp.links[c])return $gp.links[c].call(this,a,e);if("function"===
typeof gplinks[c])return gplinks[c].call(this,e,a);switch(c){case "toggle_show":$(e).toggle();break;case "inline_box":$gp.CopyVals(e,this);$.fn.colorbox($gp.cboxSettings({inline:!0,href:e,open:!0}));break;case "postlink":$gp.post_link(this);break;case "gpajax":$gp.jGoTo(this.href);break;case "creq":$gp.cGoTo(this,!0);break;case "cnreq":$gp.cGoTo(this,!1);break;case "close_message":d.closest("div").slideUp();break;default:return!0}a.preventDefault();return!1}});$("body").trigger("gpReady")});
function strip_to(a,b){if(!a)return a;var d=a.indexOf(b);return-1<d?a.substr(d+1):a}function strip_from(a,b){if(!a)return a;var d=a.indexOf(b);0<d&&(a=a.substr(0,d));return a}function jPrep(a,b){return $gp.jPrep(a,b)}function ajaxResponse(a,b,d){return $gp.Response(a,b,d)}function loading(){$gp.loading()}function loaded(){$gp.loaded()};